<?php
require_once __DIR__ . '/layout.php';
$id=isset($_GET['id'])?(int)$_GET['id']:(isset($_POST['id'])?(int)$_POST['id']:0);$row=vehicle_get_request($id);
if(!$row||((int)$row['user_id']!==(int)$_SESSION['user_id'])){http_response_code(403);die('403 Forbidden: ประเมินได้เฉพาะคำขอของตนเอง');}
if($row['status']!=='completed'){vehicle_flash('warning','สามารถประเมินความพึงพอใจได้เมื่อสถานะงานเสร็จสิ้นแล้ว');vehicle_redirect('detail.php?id='.$id);}
if($_SERVER['REQUEST_METHOD']==='POST'){
 vehicle_check_csrf();$rating=isset($_POST['rating'])?(int)$_POST['rating']:0;$comment=isset($_POST['comment'])?trim($_POST['comment']):'';if(!in_array($rating,array(1,3,5),true)){vehicle_flash('danger','กรุณาเลือกคะแนนความพึงพอใจ');vehicle_redirect('feedback.php?id='.$id);}
 $uid=(int)$_SESSION['user_id'];$stmt=$conn->prepare("INSERT INTO vehicle_feedback(request_id,user_id,rating,comment) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE user_id=VALUES(user_id),rating=VALUES(rating),comment=VALUES(comment),updated_at=NOW()");$stmt->bind_param('iiis',$id,$uid,$rating,$comment);$stmt->execute();$stmt->close();vehicle_flash('success','บันทึกความพึงพอใจเรียบร้อยแล้ว และสามารถกลับมาแก้ไขได้');vehicle_redirect('detail.php?id='.$id);
}
$fb=null;$stmt=$conn->prepare("SELECT * FROM vehicle_feedback WHERE request_id=? AND user_id=? LIMIT 1");$uid=(int)$_SESSION['user_id'];$stmt->bind_param('ii',$id,$uid);$stmt->execute();$rs=$stmt->get_result();$fb=$rs?$rs->fetch_assoc():null;$stmt->close();
vehicle_page_start('ประเมินความพึงพอใจ','ให้คะแนนบริการยานพาหนะสำหรับคำขอของคุณ คะแนนสามารถแก้ไขได้ภายหลัง','list');
?>
<section class="vehicle-card" style="max-width:760px;margin:0 auto"><div class="vehicle-card__header"><div><h2><?= vehicle_e($row['request_no']) ?></h2><p><?= vehicle_e($row['location']) ?> · <?= vehicle_format_thai_date($row['use_date']) ?></p></div><a class="vehicle-btn vehicle-btn--ghost vehicle-btn--small" href="detail.php?id=<?= $id ?>">← รายละเอียด</a></div><div class="vehicle-card__body"><form method="post"><input type="hidden" name="csrf_token" value="<?= vehicle_e(vehicle_csrf_token()) ?>"><input type="hidden" name="id" value="<?= $id ?>"><div class="vehicle-feedback-scale"><?php foreach(array(5=>'ดีมาก',3=>'พอใช้',1=>'ควรปรับปรุง') as $score=>$label):?><div class="vehicle-feedback-option"><input id="r<?= $score ?>" type="radio" name="rating" value="<?= $score ?>" <?= $fb&&(int)$fb['rating']===$score?'checked':'' ?> required><label for="r<?= $score ?>"><strong><?= $score ?></strong><span><?= vehicle_e($label) ?></span></label></div><?php endforeach;?></div><div class="vehicle-field vehicle-field--12" style="margin-top:18px"><label>ความคิดเห็นเพิ่มเติม</label><textarea class="vehicle-control vehicle-textarea" name="comment" placeholder="ข้อเสนอแนะเกี่ยวกับรถ พนักงานขับ หรือการให้บริการ"><?= vehicle_e($fb?$fb['comment']:'') ?></textarea></div><button class="vehicle-btn vehicle-btn--primary vehicle-btn--wide" type="submit">บันทึกความพึงพอใจ</button></form></div></section>
<?php vehicle_page_end(); ?>
