<?php
require_once __DIR__ . '/config_vehicle.php';
if($_SERVER['REQUEST_METHOD']!=='POST')vehicle_redirect('index.php?page=list');vehicle_check_csrf();
$id=isset($_POST['id'])?(int)$_POST['id']:0;$row=vehicle_get_request($id);if(!$row){vehicle_flash('danger','ไม่พบรายการ');vehicle_redirect('index.php?page=list');}
$uid=(int)$_SESSION['user_id'];$isOwner=(int)$row['user_id']===$uid;$canEdit=$currentVehicleIsAdmin||($isOwner&&in_array($row['status'],array('pending_supervisor','pending_admin'),true));if(!$canEdit){http_response_code(403);die('403 Forbidden');}
$type=isset($_POST['request_type'])?$_POST['request_type']:'general';if(!in_array($type,array('general','refer'),true))$type='general';$bookRef=trim(isset($_POST['book_reference'])?$_POST['book_reference']:'');$bookNo=trim(isset($_POST['book_no'])?$_POST['book_no']:'');$bookDate=!empty($_POST['book_date'])?$_POST['book_date']:null;$urgency=isset($_POST['urgency'])?$_POST['urgency']:'ปกติ';$vehicleId=isset($_POST['vehicle_id'])?(int)$_POST['vehicle_id']:0;$privateReg=trim(isset($_POST['private_registration'])?$_POST['private_registration']:'');$reason=trim(isset($_POST['reason'])?$_POST['reason']:'');$detail=trim(isset($_POST['detail'])?$_POST['detail']:'');$location=trim(isset($_POST['location'])?$_POST['location']:'');$useDate=isset($_POST['use_date'])?$_POST['use_date']:'';$useTime=isset($_POST['use_time'])?$_POST['use_time']:'';$endDate=!empty($_POST['end_date'])?$_POST['end_date']:null;$endTime=!empty($_POST['end_time'])?$_POST['end_time']:null;$driverId=isset($_POST['driver_id'])?(int)$_POST['driver_id']:0;$members=isset($_POST['members'])&&is_array($_POST['members'])?$_POST['members']:array();
if($reason===''||$location===''||$useDate===''||$useTime===''||($vehicleId<=0&&$privateReg==='')){vehicle_flash('danger','กรุณากรอกข้อมูลสำคัญให้ครบ');vehicle_redirect('edit.php?id='.$id);}
$hospitalReg='';if($vehicleId>0){$stmt=$conn->prepare("SELECT registration FROM vehicle_fleet WHERE id=? LIMIT 1");$stmt->bind_param('i',$vehicleId);$stmt->execute();$stmt->bind_result($hospitalReg);if(!$stmt->fetch()){$stmt->close();vehicle_flash('danger','ไม่พบรถที่เลือก');vehicle_redirect('edit.php?id='.$id);}$stmt->close();$privateReg='';}
$document=$row['document'];try{$document=vehicle_upload_document('document',$document);}catch(Exception $e){vehicle_flash('danger',$e->getMessage());vehicle_redirect('edit.php?id='.$id);}
$owner=vehicle_user_by_id((int)$row['user_id']);$dept=vehicle_department_for_user($owner);$super=vehicle_supervisor_for_user($owner);$superId=isset($super['id'])?(int)$super['id']:0;$superName=isset($super['fullname'])?$super['fullname']:'';
// ถ้ายังอยู่ช่วงรอรับรอง ให้รีเซ็ตไปหาหัวหน้าตามแผนกปัจจุบัน
$newStatus=$row['status'];$superStatus=$row['supervisor_status'];if(in_array($row['status'],array('pending_supervisor','pending_admin'),true)){$superStatus=$superId>0?'pending':'not_required';$newStatus=$superId>0?'pending_supervisor':'pending_admin';}
$companionRows=array();$names=array();foreach($members as $m){$mid=(int)$m;if($mid<=0||$mid===(int)$row['user_id'])continue;$stmt=$conn->prepare("SELECT u.id,u.fullname,COALESCE((SELECT p.position_name FROM personnel p WHERE p.user_id=u.id ORDER BY p.id DESC LIMIT 1),'') position_name FROM users u WHERE u.id=? AND u.status='active' LIMIT 1");$stmt->bind_param('i',$mid);$stmt->execute();$rs=$stmt->get_result();if($rs&&($p=$rs->fetch_assoc())){$companionRows[]=$p;$names[]=$p['fullname'];}$stmt->close();}
$companions=implode(', ',$names);$car=$privateReg!==''?$privateReg:$hospitalReg;$subject=$bookRef!==''?$bookRef:$reason;
$conn->begin_transaction();try{
$fields=array('request_type','book_reference','book_no','book_date','urgency','vehicle_id','hospital_registration','private_registration','reason','location','use_date','use_time','end_date','end_time','driver_id','detail','document','companions','car','subject','department_id','department_name','supervisor_user_id','supervisor_name','supervisor_status','status');
$vals=array($type,$bookRef,$bookNo,$bookDate,$urgency,$vehicleId,$hospitalReg,$privateReg,$reason,$location,$useDate,$useTime,$endDate,$endTime,$driverId,$detail,$document,$companions,$car,$subject,$deptId,$deptName,$superId,$superName,$superStatus,$newStatus);$sets=array();foreach($fields as $f)$sets[]="`$f`=?";$sql="UPDATE vehicle_requests SET ".implode(',',$sets)." WHERE id=?";$vals[]=$id;$types='';foreach($vals as $ix=>$v){if(in_array($ix,array(5,14,20,22,26),true))$types.='i';else$types.='s';}$stmt=$conn->prepare($sql);vehicle_bind_values($stmt,$types,$vals);if(!$stmt->execute())throw new Exception($stmt->error);$stmt->close();
$stmt=$conn->prepare("DELETE FROM vehicle_request_companions WHERE request_id=?");$stmt->bind_param('i',$id);$stmt->execute();$stmt->close();if($companionRows){$stmt=$conn->prepare("INSERT INTO vehicle_request_companions(request_id,user_id,person_name,position_name,level_name) VALUES(?,?,?,?,?)");foreach($companionRows as $p){$mid=(int)$p['id'];$n=$p['fullname'];$pos=$p['position_name'];$level='';$stmt->bind_param('iisss',$id,$mid,$n,$pos,$level);$stmt->execute();}$stmt->close();}
$conn->commit();vehicle_add_log($id,'edited',$row['status'],$newStatus,'แก้ไขข้อมูลคำขอ');
}catch(Exception $e){$conn->rollback();vehicle_flash('danger','แก้ไขไม่สำเร็จ: '.$e->getMessage());vehicle_redirect('edit.php?id='.$id);}
vehicle_flash('success','บันทึกการแก้ไขเรียบร้อยแล้ว');vehicle_redirect('detail.php?id='.$id);
